config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  resources :events
  resources :event_attendees
  devise_for :users
  resources :users, only: %i[index show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees

  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  scope :past, -> { where('date < ? ', DateTime.now) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'

  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: :creator_id
  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees

  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  scope :past, -> { where('date < ? ', DateTime.now) }

  def username
    m = self
    m.email.split('@')[0]
  end

  def attend!(event)
    p = self
    p.event_attendees.create!(attended_event_id: event.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def create
    @event = Event.find(params[:event_attendee][:attended_event_id])
    current_user.attend!(@event)
    redirect_to @event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    @event.creator = current_user
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    current_user = @user
    @created_events = current_user.events
    @upcoming_events = @user.attended_events.upcoming
    @prev_events = @user.attended_events.past
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div>
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
<div>
  <%= form.label :time %>
  <%= form.datetime_select :date, ampm: true, order: %i[day month year], default: 0.days.from_now.localtime %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<h1>Events page</h1>

<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event.title, event %> <small>Time: </small>
      <%= event.date%>
    </li>
  <% end %>
</ul>

<h2>Upcoming Events</h2>
<% if @events.upcoming.any? %>
	<ul>
  <% @events.upcoming.each do |event| %>
    <li>
      <%= link_to event.title, event %> <small>Time: </small>
      <%= event.date%>
    </li>
  <% end %>
</ul>
<% else %>
	<h3>No upcoming event!</h3>
<% end %>

<h2>Past Events</h2>
<% if @events.past.any? %>
	<ul>
  <% @events.past.each do |event| %>
    <li>
      <%= link_to event.title, event %> <small>Time: </small>
      <%= event.date%>
    </li>
  <% end %>
</ul>
<% else %>
	<h3>No past event!</h3>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1>Title: <%= @event.title %></h1>

<p>Description: <%= @event.description %></p>
<p><small>Time: </small><%= @event.date %></p>
<p><small>Arranged by: </small><%= @event.creator.username %></p>

<br><br>
<% if current_user && current_user != @event.creator && !current_user.attended_events.where(id: @event.id).any? %>
	<%= form_for(current_user.event_attendees.build(attended_event_id: @event.id)) do |f| %>
	<%= f.hidden_field :attended_event_id %>
    <p>Lets join this event</p>
		<%= f.submit "Attend" %>
	<% end %>
<% else %>
    <p>You are attendee of this event or you created this event or currently loged out!</p>
<% end %>

  <br><br>

<% if @event.attendees.any? %>
    <h3>Attendees list:</h3>
    <% @event.attendees.each do |attendee| %>
        <span>
            <%= attendee.email %>
        </span> <br/>
    <% end %>
<% else %>
    <h3>No attendees</h3>
<% end %><br/>


<%= link_to "See all events", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home', root_path %> | |
    <%= link_to "Create event", new_event_path %> | |
    <%= link_to "All Users", users_path %> | |

  <% if current_user %>
      <%= link_to current_user.username, current_user %> | |
    <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to "Sign Up", new_user_registration_path %>| |
    <%= link_to "Sign In", new_user_session_path %>
<% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>List of users</h1>
<% @users.each do |user| %>
<%= link_to user.username, user %> <br>
<% end %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %>'s page</h1>
<% if @created_events.any? %>
		<h3><%= @user.username.capitalize %> created (<%= @created_events.count %>) events</h3>
		
		<ul>
			<% @created_events.each do |event| %>
				<li>
				<%= link_to event.title, event %>
				</li>
			<% end %>
		</ul>

	<% else %>
		<h3>No Events Found</h3>
	<% end %>

<% if @upcoming_events.any? %>
	<h3>Upcoming Events have to attend</h3> 
	<ul>
		<% @upcoming_events.each do |event| %>
			<li>
			<%= link_to event.title, event %> <small>Time: </small>
			<%= event.date%>
			</li>
		<% end %>
	</ul>
<% else %>
	<h3>No Upcoming Events have to attend</h3>
<% end %>

<% if @prev_events.any? %>
	<h3>Previous events attended</h3> 
	<ul>
		<% @prev_events.each do |event| %>
			<li>
			<%= link_to event.title, event %> <small>Time: </small>
			<%= event.date%>
			</li>
		<% end %>
	</ul>
<% else %>
	<h3>No previous event attended</h3>
<% end %>